width: 800
height: 600
title: Test Network
nodes:
    - name: router1
      label: Main Router
      position: {x: 100, y: 100}
      icon: router.png
      monitoring: false
    - name: switch1
      label: Access Switch
      position: {x: 300, y: 100}
      icon: switch.png
      monitoring: false
    - name: switch2
      label: Access Switch
      position: {x: 300, y: 100}
      icon: switch.png
      monitoring: false
    - name: switch-test
      label: Access Switch
      position: {x: 300, y: 100}
      icon: switch.png
      monitoring: false
links: []
